### ISSUE TITLE
Pagination bug when using search or filtering feature.

### ISSUE THREAD

**Issue by mrnotepad** [Dev-Owl/advanced_datatable#25]
Pagination doesn't work when filtering only shows 10 pages. next page is not clickable or disabled.

Steps to reproduce the behavior using the demo:
1. Go to search bar 
2. Type example "a"
3. See bug.

Only displays 10 items and the pagination is not clickable.

**Comment by kkalisz** [comment]
I have checked what is wrong.
So it looks that when filtering is on, RemoteDataSourceDetails field "filteredRows" has a value corresponding to a current number of rows returned by server instead of "The total amount of rows after a filter was applied".

I think that for fixing the sample, the total number of filtered rows should be returned by api.

![image](https://user-images.githubusercontent.com/5392781/175239446-0a21590b-5037-4a8c-bf5d-0df9f87a3e13.png)
